name: Update PA URL EDL
on:
  schedule:
    - cron: '0 * * * *' # Runs automatically every single hour
  workflow_dispatch: # Allows manual executions via button click

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python Engine
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Parsing Script
        run: python parse_domains.py

      - name: Commit and Push Clean List
        run: |
          git config --global user.name "edl-bot"
          git config --global user.email "edl-bot@github.com"
          git add pa-clean-urls.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "Automated update of clean PA URLs" && git push)
